default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: phrasebook-dev

test:
  <<: *default
  database: phrasebook-test

production:
  <<: *default
  database: phrasebook
